#version: '3'
#services:
#  web:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    volumes:
#      - .:/app
#    ports:
#      - "8000:8000"
#
version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "8000:8000"

  database:
    build:
      context: .
      dockerfile: Dockerfile.db
    volumes:
      - ./django-todo/db.sqlite3:/data/db.sqlite3
    command: ["sqlite3", "/data/db.sqlite3"]

volumes:
  db_data:

